### ISSUE TITLE
Bot folder

### ISSUE THREAD

**Issue by FoxWorn3365** [galaxy119/PlayerStats#3]
I put the bot folder in the folder EXILED / Plugins / dependencies   but not work
Bot folder: EXILED / Plugins / dependencies / Bot

**Comment by galaxy119** [comment]
The bot has to be started manually, it isn't started automatically with the server, not does it's location belong in the dependencies folder.

**Comment by FoxWorn3365** [comment]
where do I put the bot folder?

**Comment by FoxWorn3365** [comment]
@galaxy119 
where do I put the bot folder?
